stages:
  - lint
  - test
  - publish

variables:
  CI_IMAGE:               "node:16.10"

.kubernetes-env:          &kubernetes-env
  image:                  $CI_IMAGE
  tags:
    - kubernetes-parity-build

lint:
  stage:                  lint
  <<:                     *kubernetes-env
  script:
    - yarn setup
    - yarn lint

test:
  stage:                  test
  <<:                     *kubernetes-env
  script:
    - yarn setup
    # - yarn test
    - echo testme

security-scan:
  variables:
    CI_IMAGE:             "aquasec/trivy:latest"
  stage:                  test
  <<:                     *kubernetes-env
  image:
    entrypoint:           [""]
  script:
    - trivy fs --exit-code 1 .
  tags:
    - kubernetes-parity-build

#TODO:
publish:
  stage:                  publish
  <<:                     *kubernetes-env
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^ci-release-.*$/
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1
  script:
    - echo tbd


