stages:
  - lint

.build:                   &build
  image:                  node:14.16
  tags:
    - kubernetes-parity-build


lint:
  stage:                  lint
  <<:                     *build
  script:
    - yarn setup
    - yarn lint


